package com.javaweb.model;
// Generated Oct 31, 2016 5:44:34 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Giaodich generated by hbm2java
 */
public class Giaodich  implements java.io.Serializable {


     private Integer idGiaoDich;
     private boolean trangThai;
     private String username;
     private String email;
     private int soDienThoai;
     private String diaChi;
     private boolean phuongThucThanhToan;
     private long tongTien;
     private Date ngayGiaoDich;

    public Giaodich() {
    }

    public Giaodich(boolean trangThai, String username, String email, int soDienThoai, String diaChi, boolean phuongThucThanhToan, long tongTien, Date ngayGiaoDich) {
       this.trangThai = trangThai;
       this.username = username;
       this.email = email;
       this.soDienThoai = soDienThoai;
       this.diaChi = diaChi;
       this.phuongThucThanhToan = phuongThucThanhToan;
       this.tongTien = tongTien;
       this.ngayGiaoDich = ngayGiaoDich;
    }
   
    public Integer getIdGiaoDich() {
        return this.idGiaoDich;
    }
    
    public void setIdGiaoDich(Integer idGiaoDich) {
        this.idGiaoDich = idGiaoDich;
    }
    public boolean isTrangThai() {
        return this.trangThai;
    }
    
    public void setTrangThai(boolean trangThai) {
        this.trangThai = trangThai;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public int getSoDienThoai() {
        return this.soDienThoai;
    }
    
    public void setSoDienThoai(int soDienThoai) {
        this.soDienThoai = soDienThoai;
    }
    public String getDiaChi() {
        return this.diaChi;
    }
    
    public void setDiaChi(String diaChi) {
        this.diaChi = diaChi;
    }
    public boolean isPhuongThucThanhToan() {
        return this.phuongThucThanhToan;
    }
    
    public void setPhuongThucThanhToan(boolean phuongThucThanhToan) {
        this.phuongThucThanhToan = phuongThucThanhToan;
    }
    public long getTongTien() {
        return this.tongTien;
    }
    
    public void setTongTien(long tongTien) {
        this.tongTien = tongTien;
    }
    public Date getNgayGiaoDich() {
        return this.ngayGiaoDich;
    }
    
    public void setNgayGiaoDich(Date ngayGiaoDich) {
        this.ngayGiaoDich = ngayGiaoDich;
    }




}


