package com.javaweb.model;
// Generated Oct 31, 2016 5:44:34 PM by Hibernate Tools 4.3.1



/**
 * Loaisanpham generated by hbm2java
 */
public class Loaisanpham  implements java.io.Serializable {


     private int idLoaiSanPham;
     private String tenLoai;
     private String moTa;

    public Loaisanpham() {
    }

    public Loaisanpham(int idLoaiSanPham, String tenLoai, String moTa) {
       this.idLoaiSanPham = idLoaiSanPham;
       this.tenLoai = tenLoai;
       this.moTa = moTa;
    }
   
    public int getIdLoaiSanPham() {
        return this.idLoaiSanPham;
    }
    
    public void setIdLoaiSanPham(int idLoaiSanPham) {
        this.idLoaiSanPham = idLoaiSanPham;
    }
    public String getTenLoai() {
        return this.tenLoai;
    }
    
    public void setTenLoai(String tenLoai) {
        this.tenLoai = tenLoai;
    }
    public String getMoTa() {
        return this.moTa;
    }
    
    public void setMoTa(String moTa) {
        this.moTa = moTa;
    }




}


